### ISSUE TITLE
create a landing page

### ISSUE THREAD

**Issue by mabroorcc** [mabroorcc/auditor#1]

**Comment by mabroorcc** [comment]
![Image](https://github.com/user-attachments/assets/2674662f-bd3e-41a1-8d94-ba34f244a314)

**Comment by mabroorcc** [comment]
something simple like above should be good
let's start designing the above with placeholder text & i will provide the details on text & links later

**Comment by usmangenx** [comment]
give hero text and description for Landing page

**Comment by mabroorcc** [comment]
updated the code with the new landing page closing this for future enhancements we can create separate issues
